spring.application.name=RAG

spring.datasource.url=jdbc:postgresql://ep-winter-unit-aiog31u8-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_sGgwnW7yzR5C&sslmode=require&channelBinding=require
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

security.jwt.secret=mynameishemantmynameishemantmynameishemantmynameishemantmynameishemantmynameishemant
security.jwt.access-exp-minutes=3
security.jwt.refresh-exp-minutes=10

openrouter.api.key=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